### PR TITLE
feature(relay): add connectionObject helper, cursorType option, and more field options

### LINKED ISSUE #89: Connections on interface
Is there any way of doing this yet?
```ts
import { builder } from '../builder';
import { PostEntity } from '../entities';

export const PageInterface = builder.interfaceRef('Page').implement({
  fields: (t) => ({
    // eslint-disable-next-line
    posts: t.connection({ type: PostEntity, resolve: () => ({} as any) }),
  }),
});
```

I tried the above but get this error when trying to use it with relay

```
Interface field Page.posts expects type PagePostsConnection! but UserNode.posts is type UserNodePostsConnection!.
```

### LINKED ISSUE #94: Relay connection cursor type
The relay connection plugin is using `ID` for cursors. Reading the relay connection spec, it clearly allows for this, but we are currently using `String` and this would be a breaking change for clients. Is it possible to configure this type? If not, we can look at a migration path.

### PR DESCRIPTION
**Pull request by hayes**
fixes #94 
fixes #89 

Preview versions:

 - @giraphql/converter@2.4.2-alpha.0
 - @giraphql/core@2.10.0-alpha.0
 - @giraphql/deno@2.9.0-alpha.0
 - @giraphql/plugin-dataloader@2.5.4-alpha.1
 - @giraphql/plugin-directives@2.3.2-alpha.0
 - @giraphql/plugin-errors@2.2.0-alpha.0
 - @giraphql/plugin-example@2.2.2-alpha.0
 - @giraphql/plugin-mocks@2.2.2-alpha.0
 - @giraphql/plugin-relay@2.9.0-alpha.1
 - @giraphql/plugin-scope-auth@2.5.0-alpha.0
 - @giraphql/plugin-simple-objects@2.4.2-alpha.0
 - @giraphql/plugin-smart-subscriptions@2.3.2-alpha.0
 - @giraphql/plugin-sub-graph@2.3.2-alpha.0
 - @giraphql/plugin-validation@2.6.1-alpha.0

### CODE REVIEW

**Comment by jamiehodge** [comment]
I will try and test this over the weekend.

**Comment by NICHTJ3** [comment]
After bumping the packages I'm getting an error `Error: undefined is not a valid type ref`

**Comment by hayes** [comment]
Did you bump core as well as the relay plugin? That would explain this error, but could be something else.

**Comment by NICHTJ3** [comment]
I don't think I bumped core but 🤷

**Comment by hayes** [comment]
If you could provide a stack trace that could be helpful (although a lot of times refs or not resolved synchronously, so it might not point at the real issue)

**Comment by NICHTJ3** [comment]
```
/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:300
    if (!ref) {
            ^
Error: undefined is not a valid type ref
    at ConfigStore.onTypeConfig (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:300:13)
    at ConfigStore.addFieldRef (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:131:12)
    at ObjectFieldBuilder.createField (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/fieldUtils/base.ts:46:30)
    at ObjectFieldBuilder.field (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/fieldUtils/root.ts:385:17)
    at Object.fields (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/plugin-relay/src/schema-builder.ts:396:15)
    at /Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/builder.ts:165:24
    at /Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:369:66
    at ConfigStore.onTypeConfig (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:303:7)
    at ConfigStore.addFields (/Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:368:12)
    at /Users/trent.nicholson/Documents/personal/iou/app/node_modules/@giraphql/core/src/config-store.ts:366:45
error Command failed with exit code 1.
```

**Comment by hayes** [comment]
Oh, nvm. Core wasn't changed in this PR, that's not the issue (unless you updated the errors plugin, I released a new version of that as well, that does require core to be updated).

**Comment by NICHTJ3** [comment]
I did upgrade the errors plugin when you merged to master the other day (I think I bumped core then)

**Comment by NICHTJ3** [comment]
Core is at v2.9.1

**Comment by hayes** [comment]
I am about to log off for the day, and I don't see any obvious ways this could be happening. 

If you wanted to debug further something that might help is modifying lib/schema-builder.js in the plugin package to look something like:

Screen Shot 2021-07-03 at 12 01 37 AM


This should log the name of the connection that is causing the issue.   If you could tell me what the code looks like that creates that connection, maybe it will give me an idea about how this is happening.  A small repro is the best way to debug, but I know it can be a bit of a pain to get set up, but I put together a simple pre-configured example (that doesn't error yet) here https://codesandbox.io/s/thirsty-franklin-xp868?file=/src/index.ts&resolutionWidth=320&resolutionHeight=675

I can try to help debug more tomorrow, but don't have much of an idea yet.

**Comment by hayes** [comment]
What I did figure out is that it seems to be the ref for the type used for the `node` field (in the image above) that is causing the issue.  This gets passed through from the `connection` unmodified.  Best guess is it's somehow related to import order or something, but hard to say without more info.  Issues related to import order are something giraphql tries to mitigate.  It could also be related to multiple plugins interacting in a weird way, so if the connection causing this issue is using other plugins (like the errors plugin) that would be good to know.

**Comment by hayes** [comment]
@NICHTJ3 just noticed your code is publicly viewable.  As suspected this is a circular import issue, and unfortunatly not something that is easy to fix in giraphql.  It is however easy to fix in your app.  Just replace `import { PostEntity } from '../entities` with `import { PostEntity } from '../entities/post';` and it should work.

**Comment by NICHTJ3** [comment]
Oh god that makes complete sense I forgot I moved the posts onto the user entity while I was debugging things. Thanks for this

**Comment by NICHTJ3** [comment]
The changes are great. The connections are cleaner and being able to have connection types be reused is amazing

**Pull request merged**
