### PR TITLE
feature: improve esm support by adding .js extensions and package.jso…

### PR DESCRIPTION
**Pull request by hayes**
…n exports

### CODE REVIEW

**Comment by hayes** [comment]
🦋  success packages published successfully:
🦋  @giraphql/converter@0.0.0-preview-20217701452
🦋  @giraphql/core@0.0.0-preview-20217701452
🦋  @giraphql/deno@0.0.0-preview-20217701452
🦋  @giraphql/plugin-dataloader@0.0.0-preview-20217701452
🦋  @giraphql/plugin-directives@0.0.0-preview-20217701452
🦋  @giraphql/plugin-errors@0.0.0-preview-20217701452
🦋  @giraphql/plugin-example@0.0.0-preview-20217701452
🦋  @giraphql/plugin-mocks@0.0.0-preview-20217701452
🦋  @giraphql/plugin-prisma@0.0.0-preview-20217701452
🦋  @giraphql/plugin-relay@0.0.0-preview-20217701452
🦋  @giraphql/plugin-scope-auth@0.0.0-preview-20217701452
🦋  @giraphql/plugin-simple-objects@0.0.0-preview-20217701452
🦋  @giraphql/plugin-smart-subscriptions@0.0.0-preview-20217701452
🦋  @giraphql/plugin-sub-graph@0.0.0-preview-20217701452
🦋  @giraphql/plugin-validation@0.0.0-preview-20217701452

**Comment by pixelmund** [comment]
So i just tested it with `@giraphql/core@0.0.0-preview-20217701452`, node still thinks it's a commonjs module

```sh
> Named export 'BasePlugin' not found. The requested module '@giraphql/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@giraphql/core';
const { RootFieldBuilder, assertArray, InputFieldBuilder, verifyRef, createContextCache, BasePlugin, mapInputFields, createInputValueMapper, isThenable, ObjectRef, InterfaceRef, resolveInputTypeConfig } = pkg;
```

The way to fix this is either to use `.mjs files` or adding a `package.json` inside the `esm folder` with the following content:

packagejson

It doesn't need to have anything other than `type module`, this is enough to let node treat the folder as esm i saw this somewhere in my node_modules

**Comment by hayes** [comment]
🦋  @giraphql/converter@0.0.0-preview-20217752147
🦋  @giraphql/core@0.0.0-preview-20217752147
🦋  @giraphql/deno@0.0.0-preview-20217752147
🦋  @giraphql/plugin-dataloader@0.0.0-preview-20217752147
🦋  @giraphql/plugin-directives@0.0.0-preview-20217752147
🦋  @giraphql/plugin-errors@0.0.0-preview-20217752147
🦋  @giraphql/plugin-example@0.0.0-preview-20217752147
🦋  @giraphql/plugin-mocks@0.0.0-preview-20217752147
🦋  @giraphql/plugin-prisma@0.0.0-preview-20217752147
🦋  @giraphql/plugin-relay@0.0.0-preview-20217752147
🦋  @giraphql/plugin-scope-auth@0.0.0-preview-20217752147
🦋  @giraphql/plugin-simple-objects@0.0.0-preview-20217752147
🦋  @giraphql/plugin-smart-subscriptions@0.0.0-preview-20217752147
🦋  @giraphql/plugin-sub-graph@0.0.0-preview-20217752147
🦋  @giraphql/plugin-validation@0.0.0-preview-20217752147

**Comment by hayes** [comment]
these are still broken.

**Comment by hayes** [comment]
🦋  @giraphql/converter@0.0.0-preview-20217752147
🦋  @giraphql/core@0.0.0-preview-20217752147
🦋  @giraphql/deno@0.0.0-preview-20217752147
🦋  @giraphql/plugin-dataloader@0.0.0-preview-20217752147
🦋  @giraphql/plugin-directives@0.0.0-preview-20217752147
🦋  @giraphql/plugin-errors@0.0.0-preview-20217752147
🦋  @giraphql/plugin-example@0.0.0-preview-20217752147
🦋  @giraphql/plugin-mocks@0.0.0-preview-20217752147
🦋  @giraphql/plugin-prisma@0.0.0-preview-20217752147
🦋  @giraphql/plugin-relay@0.0.0-preview-20217752147
🦋  @giraphql/plugin-scope-auth@0.0.0-preview-20217752147
🦋  @giraphql/plugin-simple-objects@0.0.0-preview-20217752147
🦋  @giraphql/plugin-smart-subscriptions@0.0.0-preview-20217752147
🦋  @giraphql/plugin-sub-graph@0.0.0-preview-20217752147
🦋  @giraphql/plugin-validation@0.0.0-preview-20217752147

**Comment by hayes** [comment]
Haven't done thorough testing, but I know it can at least be imported from an .mjs file now

**Comment by pixelmund** [comment]
Seems like the esm folder is empty

esm_missing

**Comment by hayes** [comment]
Looks like I pasted output from the wrong version in the second comment, that was the one that was still broken.  `20217753333` is the tag for the version that should actually work... Sorry about that

**Comment by pixelmund** [comment]
It works for me now, thank you! We probably need to verify that nothing in the cjs versions broke.

**Pull request merged**
