### PR TITLE
feature: add relayMutation method

### LINKED ISSUE #70: Add Mutations to Relay Plugin
Another feature request. Would it be possible to add a mutation type that is relay compatible? That is, it follows the [Relay Specification for Mutations](https://relay.dev/docs/v1.6.2/graphql-server-specification/#mutations).

The relay-graphql library has a [helper for this](https://github.com/graphql/graphql-relay-js#mutations) and there's a [nexus plugin](https://www.npmjs.com/package/@jcm/nexus-plugin-relay-mutation) that does something similar. 

Thanks again. I'm digging this system.

### PR DESCRIPTION
**Pull request by hayes**
fixes #70 

preview versions:
 - @giraphql/plugin-dataloader@2.2.4-alpha.2
 - @giraphql/plugin-relay@2.4.0-alpha.2

example usage:

```ts
builder.relayMutationField(
  'exampleMutation',
  {
    inputFields: (t) => ({
      id: t.id({
        required: true,
      }),
    }),
  },
  {
    resolve: async (root, args) => Promise.resolve({ status: args.input.id === '123' ? 200 : 500 }),
  },
  {
    outputFields: (t) => ({
      itWorked: t.boolean({
        resolve: (parent) => parent.status === 200,
      }),
    }),
  },
);
```

produces:

```graphql
input ExampleMutationInput {
  clientMutationId: ID!
  id: ID!
}

type ExampleMutationPayload {
  clientMutationId: ID!
  itWorked: Boolean!
}

type Mutation {
  exampleMutation(input: ExampleMutationInput!): ExampleMutationPayload!
}
```

### CODE REVIEW

**Comment by hayes** [comment]
@kesne would something similar to this work for your inline input object request?

I was thinking of adding a new plugin that adds a few new methods to builder:

`builder.queryFieldWithInput(name, inputOptions, fieldOptions)`,  `builder.objectFieldWithInput(obj, name, inputOptions, fieldOptions)`, etc

I looked at adding it to field builder, but having nested builders is weird (shadow t, or use a different name).

**Comment by litewarp** [comment]
Hey @hayes, I had a chance to check out the mutation plugin. It looks good so far. Some issues:

1. The resolver does not pass in the types for its arguments -- i.e. the arguments are not typed with the inputField object (the [Some]MutationInput!), nor is the context type extended. Do we have to manually type these?

2. Can we either (a) camelcase the mutation name when adding it to the root mutation type, or (b) allow for two separate names to be passed. Typically you would write the mutation field and then add it to the mutation object under its own separate key, like ` { createUser: FieldConstructor }`.

I'm not sure if its formally specification to have the root Query and Mutation fields be camelcase, but it's been my convention and the graphql docs [use it that way](https://graphql.org/learn/queries/#mutations). 

```JSX
// bad - root fields should be camelcase
type Mutation {
  CreateUser(...): CreateUserPayload!
}

// good
type Mutation {
  createUser(...): CreateUserPayload!
}
```

**Comment by hayes** [comment]
@litewarp resolver args should be typed automatically.  Resolver still works like a normal resolver, so everything is under the 'input' arg, which might be why it seemed like it wasn't working. Not sure what you mean by extending context though.

Regarding casing, I think it already works as you are describing, but in the opposite direction.  The name you provide is the field name (and can be camel cases).  The type names will be capitalized and based on the field name

**Comment by hayes** [comment]
I have most of the docs written, and will push up a more finished version later today

**Comment by hayes** [comment]
@litewarp published updated version (requires some extra setup to ensure comparability).  Versions in PR description, docs: https://github.com/hayes/giraphql/pull/73/files#diff-6472ed16f4d17db05920cfd46869897176c13eb2a3046bad7cdda72a5b9416e6R248

**Comment by litewarp** [comment]
Cool. Cool cool cool. Will give it a whirl when I'm back at keyboard.

**Comment by litewarp** [comment]
@hayes Not sure if this is a regression, but I'm not getting the types applied to the extended globalConnectionFields.

Screen Shot 2021-05-30 at 12 11 17 PM

**My builder config**

Screen Shot 2021-05-30 at 12 11 32 PM

**Comment by hayes** [comment]
@litewarp Nothing related to that should have changed.  What is the type of src if you hover over it?  Everything looks correct, and seems to work as expected if I set up something similar.

One thing I did notice is the extra props your passing in your SchemaTypes (User, LawFirm, PageCursors)  Unless they are bing used by a custom plugin, those won't do anything.

**Comment by litewarp** [comment]
yeah, my source is the base connection type:

**Comment by hayes** [comment]
does the context arg have your custom context type?  I can't think of any reason this would not be working.  I would try removing other props from the SchemaBuilder types, including the cursors thing so you are left with just the `totalCount: number` and see if anything else is messing it up (just to try to narrow down the issue).  I just don't see anything wrong with the setup in what I've seen so far.  It's possible you have some sort of circular reference TS can't resolve (EG one of the types passed into builder depends on builder, which would cause TS to not know how to resolve it).

**Comment by litewarp** [comment]
Yes, the context arg has the correct type.

I tried removing stuff and moving it around but couldn't get the error to work. I'm thinking it might be a circular reference but not even sure how to diagnose the error.

Here is my pageCursors file:
```Typescript
// pageCursors.ts
import builder from '../builder'

export interface PageCursor {
  isCurrent: boolean
  cursor: string
  page: number
}

export interface PageCursors {
  first?: PageCursor
  previous?: PageCursor
  last?: PageCursor
  around: PageCursor[]
}

export const PageCursorRef = builder.objectRef<PageCursor>('PageCursor')

builder.objectType(PageCursorRef, {
  fields: (t) => ({
    isCurrent: t.exposeBoolean('isCurrent', {}),
    cursor: t.exposeString('cursor', {}),
    page: t.exposeInt('page', {})
  })
})

export const PageCursorsRef = builder.objectRef<PageCursors>('PageCursors')

builder.objectType(PageCursorsRef, {
  fields: (t) => ({
    first: t.field({
      type: PageCursorRef,
      nullable: true,
      resolve: (src) => src.first
    }),
    last: t.field({
      type: PageCursorRef,
      nullable: true,
      resolve: (src) => src.last
    }),
    previous: t.field({
      type: PageCursorRef,
      nullable: true,
      resolve: (src) => src.previous
    }),
    around: t.field({
      type: [PageCursorRef],
      nullable: false,
      resolve: (src) => src.around
    })
  })
})

builder.globalConnectionFields((t) => ({
  totalCount: t.int({
    nullable: false,
    resolve: (src) => src.totalCount
  }),
  pageCursors: t.field({
    type: PageCursorsRef,
    nullable: false,
    resolve: (src) => src.pageCursors
  })
}))
``` 

And my builder file

```Typescript
// builder.ts
import SchemaBuilder from '@giraphql/core'
import { ContextType } from '../types'
import { LawFirm, Person, User, Company, PageCursors, PageCursor } from '../definitions'

import {
  AuthScopes,
  authScopes,
  relayOptions,
  DataloaderPlugin,
  MocksPlugin,
  SimpleObjectsPlugin,
  RelayPlugin,
  ScopeAuthPlugin,
  ValidationPlugin
} from './plugins'

const builder = new SchemaBuilder<{
  Connection: {
    totalCount: number
    pageCursors: PageCursors
  }
  Context: ContextType
  PageCursor: PageCursor
  Person: Person
  Company: Company
  User: User
  Lawfirm: LawFirm
  AuthScopes: AuthScopes
}>({
  // https://giraphql.com/guide/using-plugins
  // plugins executed in reverse order
  plugins: [
    MocksPlugin,
    ValidationPlugin,
    ScopeAuthPlugin,
    DataloaderPlugin,
    RelayPlugin,
    SimpleObjectsPlugin
  ],
  authScopes,
  relayOptions
})

export default builder
```

**Comment by hayes** [comment]
code you sent me seems to work fine when I try it: https://codesandbox.io/s/typescript-forked-rzhi9?file=/src/pageCursors.ts  I can help debug if you provide me with a reproduction

**Comment by hayes** [comment]
I suspect your issue is that for some reason you are including the following when creating your builder which doesn't make any sense

```
 PageCursor: PageCursor
  Person: Person
  Company: Company
  User: User
  Lawfirm: LawFirm
```

**Comment by litewarp** [comment]
Appreciate all your follow up. I read the docs about the builder types and ended up deleting all those you mentioned. Alas, I still can't get the connection types to work. I'm fully willing to admit it's something on my end and this shouldn't delay your excellent work from being merged. 

I've got to move on to other things, so I've just `@ts-expect-error my bad` for now, but I have about two or three other type issues, which I'll put up in a discussion tonight / tomorrow.

Thanks again.

**Pull request closed without merging**
